### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by yukulele** [ctlajoie/DupSelection#11]
Hi,
is it posible tu made it compatible with vscode ?

**Comment by veremenko-y** [comment]
It is already built in into VSCode

**Comment by elonmallin** [comment]
This extension is for Visual Studio and not Visual Studio Code. The extensions are completely different and it would have to be ported in that case. But VSCode already has a "duplicate" command built in. `CTRL + ALT + Down/Up` Will copy the selection or wherever the cursor is up or down. [Stackoverflow](https://stackoverflow.com/questions/30203752/how-do-i-duplicate-a-line-or-selection-within-visual-studio-code).

**Comment by yukulele** [comment]
Thank you,
I have found this vscode extension workng perfectly:
https://marketplace.visualstudio.com/items?itemName=lafe.contextualduplicate

**Comment by elonmallin** [comment]
Okey, but what is that extension doing differently than the built in command? You could also change the mapping for the built in command if you'd like. Here's the commands list https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing

Sorry if there is something I'm just not getting, looks like they are doing the same thing.

**Comment by yukulele** [comment]
some difference are discuted here:
https://github.com/Microsoft/vscode/issues/2075

**Comment by elonmallin** [comment]
Okey, yea they have some differences then, especially where the cursor is left after the duplication and that you can duplicate just a single word on the same line.
