### ISSUE TITLE
Duplicate selected lines up or down

### ISSUE THREAD

**Issue by elonmallin** [ctlajoie/DupSelection#12]
Is there any interest in adding the possibility to duplicate the selected lines up and down as opposed to always down?

There could be:
`Edit.CopySelectedLinesUp`
`Edit.CopySelectedLinesDown` Still bindable to `Ctrl+D`.

The added possibility is to bind something like `Shift+Alt+Up/Down`. This would work like in some popular text editors like [VSCode](https://code.visualstudio.com/docs/getstarted/keybindings#_basic-editing).

**Comment by elonmallin** [comment]
Found the commands are not actually the same as mentioned in #11. So the commands I'm talking about would be completely different commands.

**Comment by ctlajoie** [comment]
Sorry, I want to keep this extension as lean as possible, so I am currently not interested in adding that functionality. However I am sure there are other extensions available that will do it.
