### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by stax76** [ctlajoie/DupSelection#16]
Hello,

is Visual Studio 2019 RC3 supported?

**Comment by neoaptt** [comment]
Until the creator updates it you can do it yourself.

Change the .vsixmanifest and then build it yourself then run it.

https://github.com/ctlajoie/DupSelection/compare/master...neoaptt:patch-1

https://madskristensen.net/blog/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by ctlajoie** [comment]
I am going to try to get this plugin updated today.

**Comment by ctlajoie** [comment]
Updated the extension to v2.2 supporting VS2019
