### ISSUE TITLE
VS 2013 - Alt-d

### ISSUE THREAD

**Issue by Baudin999** [ctlajoie/DupSelection#6]
Hi,
I have a question, when I press Alt-D the line copied is not placed on a new line. Am I doing something wrong?

Example:
before
    let foo = 3

after
    let foo = 3let foo = 3

**Comment by ctlajoie** [comment]
https://visualstudiogallery.msdn.microsoft.com/830a6482-3b8f-41a8-97b5-b9c581e5ad8b
